olix_back_office:
    options:
        dark_mode: false
        navbar:
            theme: dark
            color: indigo
        sidebar:
            flat: true
            compact: true
            child_indent: true
            color: indigo
    security:
        menu_activ: true