app_olix_routes:
    # loads routes from the given routing file stored in some bundle
    resource: '@OlixBackOfficeBundle/config/routing.yml'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

